services:
  postgres:
    image: postgres
    volumes:
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    environment:
      POSTGRES_PASSWORD: postgres

  backend:
    image: ghcr.io/ikatoo/backend:dev
    ports:
      - 8000:8000
    links:
      - postgres:postgres
    environment:
      PORT: 8000
      POSTGRES_HOSTNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DBNAME: postgres
      PRIVATE_KEY: some-key
      REFRESH_PRIVATE_KEY: some-refresh-key
      CLOUDINARY_APIKEY: $CLOUDINARY_APIKEY
      CLOUDINARY_APISECRET: $CLOUDINARY_APISECRET
      CLOUDINARY_CLOUDNAME: $CLOUDINARY_CLOUDNAME
      CLOUDINARY_FOLDER: $CLOUDINARY_FOLDER
      CLOUDINARY_URL: $CLOUDINARY_URL
      SMTP_PASSWORD: $SMTP_PASSWORD
      SMTP_SECURE: true
      SMTP_SERVER_ADDRESS: $SMTP_SERVER_ADDRESS
      SMTP_SERVER_PORT: 465
      SMTP_USERNAME: $SMTP_USERNAME
      DEVELOPMENT: true

  frontend:
    image: node:20-alpine
    user: node
    working_dir: /home/node/app
    environment:
      VITE_API_URL: http://localhost:8000
      VITE_PORT: 3000
    volumes:
      - ./:/home/node/app
    expose:
      - 3000
    ports:
      - 3000:3000
    command: npx vite --host 0.0.0.0
