services:

  frontend:
    build:
      context: ../..
      dockerfile: ./docker/vite/Dockerfile
    ports:
      - 3000:80

  dev:
    image: node:20-alpine
    expose:
      - 3000
    ports:
      - 3000:3000
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    command: npm run dev
