name: E2E Tests

on: [push, workflow_dispatch]

jobs:
  e2e_tests:
    runs-on: ubuntu-latest

    env:
      VITE_API_URL: https://backend-dev-i46f.onrender.com
      VITE_PORT: 3000

    steps:
      - name: Checkout Frontend Repository
        uses: actions/checkout@v4
        with:
          ref: ${{github.ref_name}}

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Create User
        env:
          VITE_API_URL: ${VITE_API_URL}
        run: >-
          echo "VITE_API_URL"
          echo ${VITE_API_URL}
          # curl -X POST \
          # ${VITE_API_URL} \
          # -H "Content-Type: application/json" \
          # -d '{"name": "Teste", "email": "teste@teste.com", "password": "teste"}'

      # - name: Enable Test User
      #   run: PGPASSWORD=${{secrets.PGPASSWORD}}
      #     psql -v ON_ERROR_STOP=1
      #     --set "ENVSCHEMA=dev"
      #     --host ${{secrets.PGHOST}}
      #     --username ${{secrets.PGUSER}}
      #     --dbname ${{secrets.PGDBNAME}}
      #     -c 'update users set "enabled" = true;'

      # - name: Install Frontend Dependencies
      #   run: npm ci

      # - name: Run Vite
      #   env:
      #     VITE_API_URL: ${VITE_API_URL}
      #   run: docker run --name frontend
      #     -d --user=node
      #     -t -i
      #     --workdir=/home/node/app
      #     -v ./:/home/node/app
      #     -e "VITE_API_URL=$VITE_API_URL"
      #     -e "VITE_PORT=3000"
      #     --expose=3000
      #     -p "3000:3000"
      #     node:20-alpine
      #     npx vite --host 0.0.0.0

      # - name: Test
      #   run: npm run test:e2e:headless

      # - name: Enviar email em caso de falha
      #   if: ${{ failure() }}
      #   uses: dawidd6/action-send-mail@v3
      #   with:
      #     server_address: smtp.office365.com
      #     server_port: 587
      #     username: mckatoo@outlook.com
      #     password: ${{ secrets.SMTP_PASSWORD }}
      #     subject: Github Actions job result
      #     to: mckatoo@gmail.com
      #     from: iKatoo Repository
      #     html_body: Os testes E2E do repositório <a href="https://${{github.repository}}/tree/${{github.ref_name}}">${{github.repository}}</a> falharam. Por favor, verifique e corrija o código.
